#!/bin/sh

#exec 2>/var/www/olm_app_server/storage/logs/devices/tos1a/scilab/Error.txt

#echo $1 > /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt
#echo $2 >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt
#echo $3 >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

port=$(echo $1 | awk '{ print substr( $1, 8, length($1) ) }')
port="port=\"$port\";"
#echo $port >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

output=$(echo $2 | awk '{ print substr( $1, 10, length($1) ) }')
output="output=\"$output\";"
#echo $output >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

userFcn=$(echo $3  | grep -o "user_function.*")
n=${#userFcn}
input=$(echo $3 | sed "s/\(.*\).\{$n\}/\1/")
input=$(echo $input | awk '{ print substr( $1, 9, length($1) ) }' | tr : = | tr , ";")

userFcn=$(echo $userFcn  | awk '{ print substr( $userFcn, 15, length($userFcn) ) }')
userFcn='function y1=user_reg_func(t,u1,u2,u3,u4,u5,u6,u7), '$userFcn'; endfunction;'

#echo $userFcn >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

#echo $input >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

ran_from=$(dirname "$0");
#echo $ran_from >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

scilabRunFile="exec $ran_from/RunFile.sce;exit;"

identifier=$(echo -n $1 | tail -c 4)
#echo $identifier >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt

shmComm="get_shm_command='cat /dev/shm/change_input_$identifier';"
shmP="get_shm_command_P='cat /dev/shm/change_input_P_$identifier';"
shmI="get_shm_command_I='cat /dev/shm/change_input_I_$identifier';"
shmD="get_shm_command_D='cat /dev/shm/change_input_D_$identifier';"

#echo $port$output$input$userFcn$shmComm$shmP$shmI$shmD$scilabRunFile >> /var/www/olm_app_server/storage/logs/devices/tos1a/scilab/testText.txt


export SCIHOME="/home/andrej/.Scilab/scilab-5.5.2"
export DISPLAY=:1
#xhost +

scilab -d unix:1 -nw -e "$port$output$input$userFcn$shmComm$shmP$shmI$shmD$scilabRunFile"
